### ISSUE TITLE
zrepl status subcommand

### ISSUE THREAD

**Issue by woodsb02** [zrepl/zrepl#10]
It can be annoying trying to read verbose log files. It would be nice to have a command "zrepl status" which outputs to the command line the status of any jobs currently running (including progress details?), and also "zrepl list" which outputs to the command line the full suite of snapshots (and size details) available on the PC it is being run (whether they are source snapshots from this machine or pull snapshots from other machines)

**Comment by problame** [comment]
## Use Cases
### Interactive System Administration
* Instead of following log files, `gnu-watch zrepl status` is used to monitor the state of replication
### Monitoring scripts
* Machine-readable output format
* Determine age of last snapshot (`zfs list -o creation -t snapshot -s creation -r -d 1 filesystem/to/check | tail -n 1`)
* Determine if errors occurred failed (likely `zrepl status`-like feature)
    * log monitoring is actually a better fit for this...

## Implementation Concerns

* control socket is currently only accessible to zrepl user due to lack of authentication / authorization mechanisms.
* monitoring tools would likely use an HTTP API
* the same API should be consumed by the CLI frontend
* consider possibility of web-based `zrepl status` one day -> streaming interface?

**Comment by problame** [comment]
@woodsb02 It's still a bit early, but you can test the status functionality by building this branch `status_command`.
Status can be displayed using `zrepl control status`, the raw JSON exposed by `zrepl daemon` can be displayed using the `--format json` argument.

What do you think?

**Comment by problame** [comment]
- [x] Task API
- [ ] Cleanup adoption throughout zrepl
- [ ] Use show lastChanged in zrepl control status
- [ ] status command alias (does cobra allow grouping)

**Comment by problame** [comment]
merged.
