### ISSUE TITLE
push replication to multiple servers

### ISSUE THREAD

**Issue by ThomasSchlien** [zrepl/zrepl#118]
Hi,

I try to replicate my server backup via push to two different locations with zrepl. I first tried to replicate the same snapshots to two locations, but that did not seem to work. Therefore I created two different jobs with different snapshot names, but now both snapshots names are replicated to both locations. The yml configuration file is attached below. Is it even possible to replicate to two locations with zrepl?

Best regards,
Thomas

```global:
  logging:
    - type: "syslog"
      level: "info"
      format: "human"

jobs:
- name: company_to_backup
  type: push
  connect:
    type: tls
    address: "someplace.noip.me:45588"
    ca: /etc/zrepl/backup.crt
    cert: /etc/zrepl/company.crt
    key:  /etc/zrepl/company.key
    server_cn: "someplace.noip.me"
  filesystems: {
    "tank/VMs/containers<": true,
    "tank/rootfs": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^zreplloc2_"
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 7x1d | 1x30d
      regex: "^zrepl_"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"

- name: company_to_backup-location2
  type: push
  connect:
    type: tls
    address: "someotherplace.ddns.net:45588"
    ca: /etc/zrepl/backup-location2.crt
    cert: /etc/zrepl/company.crt
    key:  /etc/zrepl/company.key
    server_cn: "someotherplace.ddns.net"
  filesystems: {
    "tank/VMs/containers<": true,
    "tank/rootfs": true,
  }
  snapshotting:
    type: periodic
    prefix: zreplloc2_
    interval: 60m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^zrepl_"
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 7x1d | 1x30d
      regex: "^zreplloc2_"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zreplloc2_"```

**Comment by problame** [comment]
Thanks for using zrepl and reporting this issue!
The multi-sink use case has been considered at some point, but was deferred for a later release.
Further, in order to simplify the implementation of manual snapshotting ( https://zrepl.github.io/configuration/jobs.html#taking-snaphots ) we currently do not filter snapshot names that are considered for replication.
I'm very busy ATM (thus the late response), and will likely split up this issue into two independent features:

1. source-side snapshot filtering  
2. multi-destination replication
  2.1 support multiple replication cursors 
  2.2 somehow coordinate prune policy? or leave the mutually exclusive pruning rules to the administrator (like you already did)

**Comment by problame** [comment]
Pushing to multiple servers should now be possible & safe with zrepl 0.3. Use a `snap` job to create & prune the snapshots, configure the `push` jobs with `snapshotting: type: manual` and no prune rules, then trigger the push jobs via `zrepl signal wakeup PUSHJOBNAME`  (e.g. via cron or a shell script hook in the snap job).

The situation is not ideal because the snap job might delete snapshots that are being replicated by one or more push jobs, but zrepl 0.3 guarantees that replication won't get out of sync.

If you are successfull with this setup, I'd be happy to welcome a small write-up, preferrably as a [Quick-Start Guide for the official docs](https://zrepl.github.io/quickstart.html#configuration-examples)
