### ISSUE TITLE
systemd: add dependency on network-online.target

### ISSUE THREAD

**Issue by tdschmidl** [zrepl/zrepl#238]
I've encountered following bug from time to time:
```
zrepl version=v0.2.0-11-gdc39c81 GOOS=linux GOARCH=amd64 Compiler=gc
host zrepl[1488]: starting daemon
host zrepl[1488]: [pull_source]: starting job
host zrepl[1488]: [_prometheus]: starting job
host zrepl[1488]: [connection_loss_tidyup]: starting job
host zrepl[1488]: [connection_loss_tidyup]: wait for wakeups
host zrepl[1488]: [_control]: starting job
host zrepl[1488]: [_prometheus]: cannot listen err="listen tcp 10.0.0.200:9091: bind: cannot assign requested add
host zrepl[1488]: [_prometheus]: job exited
host zrepl[1488]: panic: runtime error: invalid memory address or nil pointer dereference
host zrepl[1488]:         panic: runtime error: invalid memory address or nil pointer dereference
host zrepl[1488]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x81ea4d]
host zrepl[1488]: goroutine 25 [running]:
host zrepl[1488]: net/http.(*onceCloseListener).close(...)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:3330
host zrepl[1488]: sync.(*Once).doSlow(0xc00018b060, 0xc0000c7bc0)
host zrepl[1488]:         /usr/local/go/src/sync/once.go:66 +0xe3
host zrepl[1488]: sync.(*Once).Do(...)
host zrepl[1488]:         /usr/local/go/src/sync/once.go:57
host zrepl[1488]: net/http.(*onceCloseListener).Close(0xc00018b050, 0xc0003a6000, 0xe0)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:3326 +0x77
host zrepl[1488]: panic(0xb1d1c0, 0x11d7d90)
host zrepl[1488]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
host zrepl[1488]: net/http.(*onceCloseListener).Accept(0xc00018b050, 0xc000120020, 0xb0fd20, 0x11d7ce0, 0xbee6e0)
host zrepl[1488]:         <autogenerated>:1 +0x32
host zrepl[1488]: net/http.(*Server).Serve(0xc0003a6000, 0x0, 0x0, 0x0, 0x0)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:2896 +0x286
host zrepl[1488]: net/http.Serve(...)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:2468
host zrepl[1488]: github.com/zrepl/zrepl/daemon.(*prometheusJob).Run(0xc000109940, 0xd19ec0, 0xc00018a930)
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/prometheus.go:75 +0x23e
host zrepl[1488]: github.com/zrepl/zrepl/daemon.(*jobs).start.func1(0xc0000f68c0, 0xd22c40, 0xc000116ee0, 0xd1ba4
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/daemon.go:220 +0x121
host zrepl[1488]: created by github.com/zrepl/zrepl/daemon.(*jobs).start
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/daemon.go:216 +0x52e
host systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
host systemd[1]: zrepl.service: Failed with result 'exit-code'.
```

My workaround for this was adding network-online dependency to the systemd-file:
/lib/systemd/system/zrepl.service
```
[Unit]
...
Wants=network-online.target
After=network-online.target
```

Maybe there should be added an `Restart=on-failure` too

**Comment by problame** [comment]
`Restart=on-failure` is potentially attractive for an attacker trying to get remote code execution, as it gives them "infinite" retries (generally, IMHO, daemons that crash frequently in production shouldn't be in production in the first place).

I only just learned about `network-online.target`: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

>  It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up), its primary purpose is network client software that cannot operate without network.

I think zrepl falls into the category where we don't want to depend on network-online.target, e.g. because we want snapshot management to continue working even if we are not connected.
Systemd provides you the `override.conf` functionality, see `systemctl edit zrepl`. This is probably the way to go for you.

Regardless, the given crash is a bug and will be fixed.

**Comment by problame** [comment]
For future reference: the following snippet should do if we wanted listeners to re-try binding to an address that is not yet configured on a local interface:
https://gist.github.com/problame/bc2372e6b6acb7a586a7654860fc6dc5

**Comment by problame** [comment]
Above commits should fix the crash and are included in https://github.com/zrepl/zrepl/releases/tag/v0.2.1
As long as there are no other crashes caused by absence of bind IPs, I'll remove the `bug` and leave this open for future discussion.

> 
> For future reference: the following snippet should do if we wanted listeners to re-try binding to an address that is not yet configured on a local interface:
> https://gist.github.com/problame/bc2372e6b6acb7a586a7654860fc6dc5
> 
> However, a quick code search around GitHub doesn't yield any other projects doing this (also in other languages). Would this pose a security problem / admin confusion?

Other issues are more pressing than this ATM, so if anyone is willing to do the security research and write a patch that uses the Gist example in zrepl, please feel free to take a shot.

**Comment by juergenhoetzel** [comment]
I encountered the same issue: I bind to a wireguard VPN ip.

My pull request #260  uses `IP_FREEBIND sockopt` as suggested in the [NetworkTarget documentation](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#whatdoesthismeanformeadeveloper)
