### ISSUE TITLE
Property Replication

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#24]
Right now, all `zfs send` invocations on the sending side are without `-p`, meaning we do not replicate any properties.

On the receiving side, as a safeguard, we override `mountpoint` in order to protect ourselves from a malicious `sender` that is trying to mount over some filesystem on the backup server.

This is more of a theoretical advantage and I'm investigating better solutions, e.g. `zfs receive -x all`, see https://github.com/zrepl/zrepl/wiki/ZFS-Feature-Support-&-Wishlist#zfs-receive--x-all

## Agenda
- [ ] Find a way how property replication should work
  - Where to store properties on receiver?
  - Protect against malicious sender (`zfs receive -x all`)
  - Think about restore procedures
- [ ] Implement it
- [ ] Document it (refs #23 )

**Comment by InsanePrawn** [comment]
Bump because I really want this.

Properties are far more than 'a little ZFS metadata' and influence how the system boots and works. Not replicating them is a missing part of the backup to me and causes system restores to be awfully manual.

I suspect the description has gone a little stale, since from what I understand, we actually DO NOT `zfs recv -o mountpoint=none`, or is that supposed to be future work?
Your words from #259:
> We currently do not set the -o mountpoint=none flag on receive, thus the receiving side inherits whatever root_fs has set as mountpoint property. All my personal systems have a root_fs with mountpoint=none, so I guess I just never ran into that.


> Right now, all `zfs send` invocations on the sending side are without `-p`, meaning we do not replicate any properties.
> 
> On the receiving side, as a safeguard, we override `mountpoint` in order to protect ourselves from a malicious `sender` that is trying to mount over some filesystem on the backup server.
 
I, as an adult sysadmin, would like to be able to enable `zfs send -p | zfs recv -o mountpoint=none` in zrepl at my own risk. Not everyone completely distrusts their backup sources so that they'd rather lose properties than risk some sort of property override. `mountpoint=none` is protection enough for me.

> ## Agenda
> 
>     * [ ]  Find a way how property replication should work

`zfs send -p`
       
>       * Where to store properties on receiver?

Just let zfs handle it. 🤷‍♂️ Easy!

>       * Protect against malicious sender (`zfs receive -x all`)

I'll take the """insecure""" `-p` over nothing any day, feel free to flood the docs with big red warnings.
If you come up with a superior mechanism later, you can always deprecate this.

>       * Think about restore procedures

Letting zfs store the properties as-is rather than some out-of-band format brings the advantage of enabling `zfs send -b` to send the original property values for restore or second level backup targets. And unlike the out of band format, it even works without zrepl. No backup software lock-in, yay!

Want a standby host? Moving it from standby to active will be a few (typically <5 I suspect) `zfs rename`s, a `zfs inherit -rS mountpoint` and maybe a reboot away.

Using zrepl for an absolutely identical second-level backup would only be a small-ish PR for a `send -b` toggle away.

Both `-p` and `-b` should fit nicely to `encrypted` in the recently added send config.

**Comment by problame** [comment]
My main problem with `-p` is that, afaik, the receiving-side properties are not versioned per snapshot - you only ever have the most recent copy of the properties on the receiving side.

If you would like to play around with `-p`, you can do that right now by inserting a mock ZFS in the PATH of the daemon. See `platformtest/logmockzfs/zfs` for a starting point. That mock script would check if `argv` is `zfs send ...` and insert the `-p` flag there. On the receiving side, do the same for `zfs recv -o mountpoint=none`.

Could you verify that this hack does what you want?

**Comment by InsanePrawn** [comment]
`send -p | recv -o mountpoint=none` does seem to work as intended for me so far, only tested with `encrypted: true` in zrepl so far though.

while a static `mountpoint=none` override would be _fine_ for the beginning, a way to specify arbitrary job-wide static overrides would be nice, for example for  `-o org.openzfs.systemd:ignore=on`, so that this pesky foreign encryption root doesn't screw up your boot process if you use the systemd generator. The code could be copy pasted for `recv -x $prop` support then.

**Comment by awehrfritz** [comment]
+1 for implementing this feature. ZFS properties are just such an awesome feature that it would be bad to loose them for backups.

@InsanePrawn seems you have made some progress, let me know if/when you need someone to test this.

**Comment by InsanePrawn** [comment]
> @InsanePrawn seems you have made some progress, let me know if/when you need someone to test this.

Yes, there's an open pull request: #285
It's a working basic prototype. If you figure out how to compile zrepl from that branch, you can test it today.
At this point there's no tests for it yet; it has only been manually tested on my machine, so don't run it on anything important, just in case.

See the PR description for the current config syntax and feel free to join the discussion on default overrides over there.

**Comment by eoli3n** [comment]
https://github.com/zrepl/zrepl/blob/66946df7560395aa6409340db1b77aafddaa7d36/docs/configuration/overview.rst#limitations

As it is merged, is that still a limitation or not ?

**Comment by problame** [comment]
No it is not. See https://zrepl.github.io/configuration/sendrecvoptions.html?highlight=property#a-note-on-property-replication for caveats. 
Would you like to fix the doc that you liked yourself?
