### ISSUE TITLE
holds: add subcmd to clean up

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#278]
Due to repeated replication failures (I suspect), a single dataset built up around 400 snapshots, 95% of which were held by a single zrepl job.
Cleaning that up was not fun, as the holds (correctly) stopped me from nuking everything with a simple `destroy -r` (or at least `-d1`).

Hence, I suggest to add some form of cleanup sub command to `zrepl holds`, e.g. `zrep holds clean [$jobname]`
I'm not sure if (for every job type) multiple snapshots of the same dataset locked by a single job is a valid situation. If not, that's a situation we can detect and fix by deleting all but the newest(?) snapshot's hold of the same name/job.
Otherwise/furthermore, I'd like a `zrepl holds release [-r] $dataset [$jobname]`, which [optionally recursively] removes all holds by all or a specified zrepl job, note the mandatory dataset argument.
Useful for quickly clearing out zrepl holds before nuking something, still leaving foreign holds intact.

I strongly suspect that zrepl is in a much better position to do some smart hold cleaning for me than my brutish shell loops, even with `zrepl holds list`.

**Comment by problame** [comment]
> Due to repeated replication failures (I suspect), a single dataset built up around 400 snapshots, 95% of which were held by a single zrepl job.

Interesting, the replication code _should_ clean up stale holds. Will investigate that. What kind of replication failures are we talking about here? Link down? 

Please open a _separate issue for this problem_, this is a release blocker for 0.3.
Please include any logs of the timestamps of the replication failure.
Preferrably in debug mode if you can reproduce the problem, but really anything for starters.

> Hence, I suggest to add some form of cleanup sub command to zrepl holds, e.g. zrep holds clean [$jobname]

`zrepl holds release --all` or `zrepl holds release --job JOBNAME` would be my preferred syntax.
I was hoping that a) the need to fix stale holds wouldn't come up because zrepl _should_ do that on its own, and b) the JSON output would make it easily usable with `jq`.

**Comment by InsanePrawn** [comment]
The holds are a leftover from the replication failures in #277

> `zrepl holds release --all` or `zrepl holds release --job JOBNAME` would be my preferred syntax.
> I was hoping that a) the need to fix stale holds wouldn't come up because zrepl _should_ do that on its own, and b) the JSON output would make it easily usable with `jq`.

Works for me!
While the JSON output is nice for scripting, for "everyday" features like "clear this dataset of your holds so I can destroy it" I'd prefer to have a stable zrepl feature for this, so I do not to have to get into my untrustworthy scripts (that break half the time). 
Or more abstractly speaking: I want zrepl to provide [the tools for] full lifetime management for the holds it creates.

**Comment by problame** [comment]
OK, let's see whether we can squeeze this in for 0.3.
The code for this is fairly straight forward, see `client/holds.go`.
Would you like to hack on that? See the `list` subcommand for how to get the list of holds.
