### ISSUE TITLE
zfs-abstractions release is racy with FS activity

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#318]
From testing #313 
`client: zrepl version=v0.2.1-62-g456dc79 GOOS=linux GOARCH=amd64 Compiler=gc`

Loses races against a running pruner and either exits like
```
list endpoint abstractions: list endpoint abstractions on "yolopool/data/zrepltest9@zrepl_20200430_131729_000": get hold on snap: zfs exited with error: zfs holds failed: exit status 1
stderr:
cannot open 'yolopool/data/zrepltest9@zrepl_20200430_131729_000': dataset does not exist
no datasets available
```

or even crashes (edit by @problame see #320 )

**Comment by problame** [comment]
These are two separate issues, splitting them up for you

**Comment by problame** [comment]
The [panic got fixed a long time ago](https://github.com/zrepl/zrepl/issues/320).

The [current handling of errors](https://github.com/zrepl/zrepl/blob/908807bd59d8fa76bf4db51b4ca64466fba65ae1/internal/client/zfsabstractions_list.go#L78-L98) is that we print them but otherwise continue and finally exit with an error.

I think that is reasonable.
