### ISSUE TITLE
Consider using zfs send -I rather than -i where appropriate

### ISSUE THREAD

**Issue by jwittlincohen** [zrepl/zrepl#354]
I setup a new replication job with an initial size of about 59TB.  As a result, it took about a day to complete the replication.  Upon completion, there were 85 snapshots for each dataset within the job that were sent, one by one, with zfs send -i.  In this circumstance, it would be a lot faster to do `zfs send -I fs@oldestsnap fs@newestsnap`, which would send all the intermediary snapshots in a single zfs send.  I imagine this would also help in the situation where a network issue prevents replication for an extended period.

**Comment by problame** [comment]
There are a number of problems with using `-I` (or `-R` for that matter):

- As [explained here](https://zrepl.github.io/v0.3.0-rc2/configuration/overview.html#how-replication-works), zrepl attempts to replicate all matching filesystems evenly:
  > Perform replication steps in the following order: Among all filesystems with pending replication steps, pick the filesystem whose next replication step’s snapshot is the oldest.

  This is not easily possible with `-I`
- We want to reserve ourselves the option to implement a snapshot filter, e.g. only replication snaphots matching a certain regex (feature request: #248 ). We wouldn't be able to implement such a filter with `-I`, thus, if we wanted to support both snapshot filtering and `-I`, we'd need to add additional logic to make those options mutually exclusive.

- 0.3 creates a `zfs hold` on `from` and `to` for the duration of a replication step in order to guarantee resumability. We can't do that if we don't know which step we are currently taking (because `zfs send -I` doesn't report them).
- simliar argument for replication_cursor, etc.
