### ISSUE TITLE
The timestamp format is non-standard, but could be

### ISSUE THREAD

**Issue by grahamc** [zrepl/zrepl#465]
Using the current timestamp format incurs a cost for everybody, since it isn't a standard and trivially readable format. Might I propose changing the format to something more standard? For example, ISO8601 supports:

* `%Y-%m-%dT%H:%M:%SZ`
*  `%Y-%m-%dT%H%M%SZ`

both of which should be no trouble for ZFS.

**Comment by problame** [comment]
Since we don't use the date embedded in the snapshot name for anything (zrepl uses the `creation` property's value), I suppose there's nothing that speaks against this for clean installations.
Not sure how we can/should deal with existing installations, though.
- do nothing? (it would work just fine!)
- provide a migration command that renames the snapshots?

Side note: I learned recently that a user was surprised that zrepl doesn't use the snapshot name to extract the data.

**Comment by problame** [comment]
As soon as we have a justification for either of the options above, I'm happy to accept a PR that implements the change and documents it.

**Comment by grahamc** [comment]
I don't have opinions on a migration command or not, but my inclination would be to do nothing by default: people might have recorded snapshots somewhere, or want to track them through logs, etc.

**Comment by grahamc** [comment]
PR opened: https://github.com/zrepl/zrepl/pull/466 I suspect you imagined more docs, though?

**Comment by Debilski** [comment]
Hi, I am not sure if a colon is the best idea in case the file system tree is exported via samba. Windows will do the weirdest things with the name (see https://unix.stackexchange.com/questions/299130/samba-how-to-display-files-with-colon-in-their-names). Rather than relying on a workaround which may or may not work, it might be better to avoid using the colon altogether.

Also, from a standpoint of making the snapshot names easier to interpret, would it be possible to add an option that rounds that timestamp? If I schedule 6 snapshots a day, I guess I don’t care too much about the exact second an individual snapshot was taken (*)(probably not even the exact minute) but more that all snapshots in the sub zfs share the same name.

(*) This is assuming that there are other ways to get that information.

**Comment by grahamc** [comment]
Good point @Debilski, I didn't know that. We could drop the colons and remain ISO8601 compliant.

**Comment by problame** [comment]
> Also, from a standpoint of making the snapshot names easier to interpret, would it be possible to add an option that rounds that timestamp? If I schedule 6 snapshots a day, I guess I don’t care too much about the exact second an individual snapshot was taken (*)(probably not even the exact minute) but more that all snapshots in the sub zfs share the same name.

How about some GUID-like identifier that is included in the snapshot name? Maybe _instead_ of a timestamp? Like `@zrepl_626246d6-c936-4c55-934a-fce3a59dd85c`? Or more compactly, `@zrepl_duihG0GHGEqAq4Pj2VoLIg`?

* Pro: doesn't suggest to the user that zrepl interprets the timestamp in the snapshot name in any way
* Con: Suggests to user that snapshots with the same name were taken in the same txg. We would like that to be the case ( ref #62 ) but snapshot hooks and other stuff make this problematic.

We could also have both, like `@zrepl_duihG0GHGEqAq4Pj2VoLIg_2006-01-02T150405.000Z`.

**Comment by Debilski** [comment]
From an admin perspective, I don’t actually mind the name of the snapshot (perhaps there could be `zrepl list-snapshots` command at some point that shows some advanced info if necessary).

My use case is that we expose the .zfs directory of our shared fs to our users, so that they can easily restore some old data in case they’ve accidentally deleted something. We currently use a `zfs-snapshot` script in `/etc/periodic` to handle the snapshotting, which results in snapshot names such as `@hourly-2021-04-19-08` and `@daily-2021-04-18`. Next to this, we have `zrepl` creating its own snapshots and we just tell our users to ignore these. (That could be a pro argument for only having indigestible GUIDs in the name.)

This works perfectly well for us, but if `zrepl` had an option to give us a similar naming scheme as the `zfs-snapshot` script (so we could stop using that script) this would be even better.

**Comment by problame** [comment]
@Debilski interesting use case, thanks for describing it.

Two thoughts I had about your deployment thay might take this a little off-track:

* Wouldn't an even better solution for your situation be to have zrepl not take any snapshots and instead replicate the ones that are created by `zfs-snapshot`?
* If zrepl supported the `hourly`, `daily`, etc. "tier" scheme for snapshots as an alternative to the current pruning grid, would that be a reason to switch user-facing snapshot management from `zfs-snapshot` to `zrepl`?

**Comment by InsanePrawn** [comment]
> This works perfectly well for us, but if `zrepl` had an option to give us a similar naming scheme as the `zfs-snapshot` script (so we could stop using that script) this would be even better.

I'm a little confused as to what exactly you want - are you looking for the snapshotting 'tiers' a la "daily" or for cleaner timestamps a la ISO?
I'm not sure why exactly you currently tell people to ignore the zrepl snapshots. admittedly, the current date format is a little dense, so would switching to the proposed ISO format be the fix for your use case?
From my understanding, you want
- ISO date format
- rounding of timestamps (to achieve identical snapshot names across datasets?)

If I understood this correctly, we should probably discuss rounding timestamps vs something like
```yml
job:
  name: foo
  snapshotting:
    interval: 4m
    global_timestamp: true
```
which would generate a timestamp every time the job's snapshotter is initiated and use that for all datasets (not sure if problame will like this :P )
While the first is somewhat aesthetical, the latter is an actual guarantee for the naming (`zrepl signal wakeup thejob` at 12:59:24 could be fun with just rounding).
I could see use cases for either/both. If there's interest we should probably discuss them in separate issues though.

**Comment by Debilski** [comment]
> Wouldn't an even better solution for your situation be to have zrepl not take any snapshots and instead replicate the ones that are created by zfs-snapshot?

Yeah, I think it was related to the pruning policy on the remote receiver. It seemed easier to handle both snapshotting logics separately. The current approach also works reasonably well, so there is no real *need* for us that anything is changed within zrepl.

> If zrepl supported the hourly, daily, etc. "tier" scheme for snapshots as an alternative to the current pruning grid, would that be a reason to switch user-facing snapshot management from zfs-snapshot to zrepl?

Definitely. Although, I think I could probably already build this with different snapshot prefixes and intervals. The main difference would be that for the hour/day/month scheme to work most reliable (predictable), zrepl would need an OnCalendar-like setting rather than an interval. I’d prefer that I know that all the daily snapshots are taken around the same time, say, 1:00 am. (And then the snapshot name could just be the date/time of intent, not the time of the actual execution. Perhaps with a `format: daily-%Y%m%d` parameter.)
I’d completely understand it, though, if this is out of the scope for zrepl, especially as there are already tools that I can use for this.

> I'm a little confused as to what exactly you want - are you looking for the snapshotting 'tiers' a la "daily" or for cleaner timestamps a la ISO?

Indeed, I hadn’t thought it through completely. I don’t really want rounded timestamps (with zeros) but rather more or less predictable tiers.

> I'm not sure why exactly you currently tell people to ignore the zrepl snapshots. admittedly, the current date format is a little dense, so would switching to the proposed ISO format be the fix for your use case?

Honestly, we don’t tell anyone to ignore the zrepl snapshots, I just expect it to be the case that our users ignore them, since the `@daily-2021-04-18` ones are just easier to parse. :)


My main concern is that with an external tool for making snapshots, one has to resort to messing with regexes to get the logic for syncing and pruning correctly which can be error-prone. I’ve created a [new issue](https://github.com/zrepl/zrepl/issues/474) with some ideas that might be useful.

**Comment by jtagcat** [comment]
## Current status
![image](https://user-images.githubusercontent.com/38327267/178739578-7b37cb0e-4604-4869-90ba-ca3f83735535.png)

zrepl is non-standard and hard to read. Sanoid shown above in image.

## New format
### Colon in new format
Windows Samba clients rename filenames (`.zfs` directory) with a random name when using colons. This is still the case, but catia (linked above) can be used to map colons to something else (including "").

Date standards intentionally provide no alternative to colons, as any known alternatives make time much less readable without context or training.

### ~~(G)UID in new format~~
It was offered to use non-readable GUID in snapshot names to indicate that zrepl does not use the date.

I'm against this, as then it is much less readable, and the GUID itself could be read as 'do not touch'. Whether an admin reads the display name as used or not doesn't really matter. It can just be a sentence in the docs.

As for unique identification, the date in name is good enough, ZFS also provides an internal GUID, if needed.

## Switching
Besides logs and in-progress transfers, the name isn't used. Date comes from ZFS properties.

### Migrating old format to new
Clean installations: go for it

As all snapshots zrepl accounts aren't made by zrepl, how do you detect whether an old format is being used, and reliably rename them?

I suggest to just start using the new format after a minor release. Users have already been previously told to upgrade manually. Plus, it will appear in changelogs.  
For most, it will break nothing. Only home-made shell scripts will be broken.

As for opt-in renaming, I'd keep it as a hidden command mentioned in the changelog. Otherwise it will bloat the help section. It should consume a prefix and an input (dataset), then opportunistically rename.

**Comment by problame** [comment]
> Windows Samba clients rename filenames (.zfs directory) with a random name when using colons. This is still the case, but catia (linked above) can be used to map colons to something else (including "").

What is `catia` ?

**Comment by problame** [comment]
@jtagcat ok, so, what are you proposing? I'm sorry, but I can't parse your style of writing

**Comment by jtagcat** [comment]
Change it to `zrepl_2022-07-13_13:00:00Z`. Switch to it with a minor release.

**Comment by problame** [comment]
@jtagcat Is vfs_catia even relevant here? My main concern is with people who are using zrepl today and have samba [vfs_shadow_copy2](https://www.samba.org/samba/docs/current/man-html/vfs_shadow_copy2.8.html) configured with a `shadow:format` that assumes the current naming scheme.
We'll break those setups by switching to the new naming scheme.

Suppose we decide to switch, how can operators of existing installations make snapshots created before _and_ after the change  available as shadow copies?
E.g., is it possible to use vfs_shadow_copy2 twice, or make it match two different `shadow:format`?

**Comment by sabirovrinat85** [comment]
> @jtagcat Is vfs_catia even relevant here?

vfs_catia is used only to represent windows forbidden characters in a directory and file names in samba share, like colon (and there's where it arises questions about date format, but it's nothing about zrepl, they should use catia probably whenever possible)

**Comment by problame** [comment]
> Suppose we decide to switch, how can operators of existing installations make snapshots created before and after the change available as shadow copies?
> E.g., is it possible to use vfs_shadow_copy2 twice, or make it match two different shadow:format?

Can we get an answer to this?

**Comment by jtagcat** [comment]
> > Suppose we decide to switch, how can operators of existing installations make snapshots created before and after the change available as shadow copies?
> > E.g., is it possible to use vfs_shadow_copy2 twice, or make it match two different shadow:format?
> 
> Can we get an answer to this?

Via `vfs_catia`.
