### ISSUE TITLE
consistently use our custom 'day' and 'week' duration units everywhere in config

### ISSUE THREAD

**Issue by Greek64** [zrepl/zrepl#486]
According to the [documentation](https://zrepl.github.io/configuration/misc.html#durations-intervals) we can use following units to state intervals:
>  s = second, m = minute, h = hour, d = day, w = week (7 days)

But the `d` and `w` units fail with
```
cannot unmarshal !!str `1d` into time.Duration
```

My guess is that `zrepl` uses the [golang duration format](https://golang.org/pkg/time/#ParseDuration), which means that the valid units are `"ns", "us" (or "µs"), "ms", "s", "m", "h"`. Which due to the regex pre-filtering reduces itself to `"s", "m", "h"`

**Comment by problame** [comment]
Thanks for reporting this inconsistency!

What is stated in the docs is true for the `grid` keep rule type:

https://github.com/zrepl/zrepl/blob/0ceea1b792118453d792a8e25ecacdc8d8284ae1/config/config.go#L660-L695

But it isn't true for all the other places in `config/config.go` where we just use `time.Duration` and let package `yaml-config` deal with it. Since we already using a customized YAML parser, we might as well add the `d` and `w` to `yaml-config`

https://github.com/zrepl/zrepl/blob/a58ce74ed0c804651a6bb2c49bcb3fda68f2c0b5/go.mod#L41

**Comment by kpfleming** [comment]
Just ran into this too (new user), would be a nice improvement since my pruning intervals are quite long (snapshots are only made once per day).
