### ISSUE TITLE
`zrepl status` only reports half the true transfer rate

### ISSUE THREAD

**Issue by Malvineous** [zrepl/zrepl#497]
I am copying a new filesystem for the first time, and I notice that the speed indicator seems quite wrong.  My other monitoring software is reporting between 300-600 MB/sec however `zrepl status` is only showing 90-150 MiB/s:

    Started: 2021-06-26 19:53:37 +1000 AEST (lasting 22m51s)
    Progress: [=|-------------------------------------------------] 382.5 GiB / 10.1 TiB @ 149.3 MiB/s

Unless my maths are wrong, 22m51s is 1371 seconds, and 382.5 GiB in 1371 seconds is 285 MiB/s.  zrepl seems to be reporting only half the actual speed.  Sure enough if I look at the actual filesystem values reported by zrepl, they are increasing by around 0.3 GiB/sec, double the reported speed.

I tried to find in the code where this is calculated and it looks like it might be at https://github.com/zrepl/zrepl/blob/master/client/status/viewmodel/bytesprogresshistory.go#L42 but there's some weird factor in play, so I'm wondering whether this is making the calculation come out wrong?  It looks like it's designed to gradually creep up to the true speed but despite leaving it for 10 minutes, it only ever shows around half the true speed.

**Comment by Malvineous** [comment]
I tried experimenting with the `factor` value and `1.0` gives me an accurate speed reading but anything less than this and the displayed transfer speed is consistently lower than what it really is.

I guess because it starts off at `0.0` and that value is carried forward forever thanks to the factor, it never recovers and never reaches the true speed.

**Comment by problame** [comment]
It's an exponentially moving average which we update every time we poll.
The poll interval is controlled via this variable (default: 1s)

https://github.com/zrepl/zrepl/blob/master/client/status/status.go#L29

Here's the expected behavior for different factors.

![image](https://user-images.githubusercontent.com/956573/123623812-2c576980-d80e-11eb-87f2-d75dfecebb30.png)

If you poll faster (i.e., change `--delay`), the faster updates will compress the curve on the x-axis.

Action items:

* experiment with picking a higher factor (you already did that)
* choose the factor depending on `--delay` to compensate for the compression/dilation of the x-axis
  * More precisely, don't use `--delay` but the actual `deltaT` to compute the weighing

There's also #339  (rate-limiting), so we'll eventually need to be more precise about transfer rates and move the logic into the daemon. But in the meantime, we can tackle the items above easily.

@Malvineous, since you seem to be able to compile zrepl and hack on Go code, would you like to continue working on this?

**Comment by calistoc** [comment]
I did some checks and I saw the same problem, from Linux I saw a transfer rate of about 80MiB/s while zrepl only reported about 30 MiB/s, this is more noticeable while replicating single snapshots of 4 GB or bigger.

I’m not sure where the problem was as I was not able to debug it, but rewriting a little the Update function I think I was able to fix it. I left the factor to 0.3 and the transfer rate looks ok now.

```
func (p *bytesProgressHistory) Update(currentVal int64) (bytesPerSecondAvg int64, changeCount int) {

        if p.last == nil {
                p.last = &byteProgressMeasurement{
                        time: time.Now(),
                        val:  currentVal,
                }
                return 0, 0
        }

        if currentVal > p.last.val {
                p.changeCount++
                p.lastChange = time.Now()

                deltaV := currentVal - p.last.val
                deltaT := time.Since(p.last.time)
                rate := float64(deltaV) / deltaT.Seconds()

                factor := 0.3
                p.bpsAvg = (1-factor)*p.bpsAvg + factor*rate

                p.last.time = time.Now()
                p.last.val = currentVal
        } else {
                p.last = nil
                return 0, 0
        }

        return int64(p.bpsAvg), p.changeCount
}
```

In case I may submit a PR

**Comment by calistoc** [comment]
yes it resets the average but only when it stops sending data, so only when currentVal == p.last.val

problem with me was that the zrepl speed was never able to go above the 30MiB/s, neither with --delay of 1s nor 3s, my guess is that this is caused by the p.last reset every 3 seconds that I was not able to understand why it was done in that way:
```
	if time.Since(p.lastChange) > 3*time.Second {
		p.last = nil
		return 0, 0
	}
```
if the "return 0, 0" will also reset the p.bpsAvg - somewhere else - that would explain why the transfer rate is not able to go up.
As said this is only a guess as I was not able to debug the interactive zrepl status.

As reported by @Malvineous I also tried factor = 1.0 and the transfer rate was ok, either with --delay 1s or 3s, anyway if I get it correctly having factor to 1.0 will basically mean instant speed with no exponentially moving

**Comment by problame** [comment]
> As reported by @Malvineous I also tried factor = 1.0 and the transfer rate was ok, either with --delay 1s or 3s, anyway if I get it correctly having factor to 1.0 will basically mean instant speed with no exponentially moving

IIRC the original `zrepl status`'s delay value was 300ms which was the value at which it felt 'active' and 'responsive'.
If people are fine with refreshes every 1s or every 3s, we might as well do away with the client-side averaging altogether. At some point in the future, we'll have daemon-side transport rate-limiting and can reuse the measurement for `zrepl status`.

**Comment by dcdamien** [comment]
The same here, zrepl's transfer rate is about half of the real speed measured by interface stats and amount of data moved over the time.
