### ISSUE TITLE
Various issues and feature requests

### ISSUE THREAD

**Issue by siilike** [zrepl/zrepl#536]
I have just tried out zrepl and run into various issues. Some of those likely already have tickets.

1. zrepl replicates all snapshots, not only the ones it takes itself. It would be nice to have a feature to filter snapshots by name. This should be possible using the `-i` flag of `zfs send`. Would the non-zrepl snapshots be removed when pruning by time/last_n?
2. For push jobs `snapshotting` is mandatory. It would be nice to be able to use the push job when snapshots are created externally, e.g. check for new snapshots every minute and/or when a signal is received. The same applies for pull jobs.
3. For push jobs `pruning.keep_receiver` is mandatory. Sometimes it makes sense to do the pruning in destination/manually instead. Currently this can be resolved by using a regex that never matches.
4. There is no option for a receive-only sink job. For better security it would be nice to limit what the remote is able to do (read/write/override/metadata/everything). The same applies to source jobs.
5. zrepl runs as root. For additional security via `zfs allow` it would be great to run zrepl as a less-privileged user instead. Maybe this already works fine, but definitely something to test.
6. There is no pruning option for the remote. It would be great to have a separate job just for pruning. The snap job likely has `snapshotting` mandatory, so it wouldn't work.
7. Buffering. It would be great to be able to specify the size of a buffer for both sending and receiving, so network and disk bottlenecks are at least somewhat mitigated, e.g. when the sink has lots of memory, but slow disks. Adding `mbuffer` in between would already work.

**Comment by problame** [comment]
> 1. zrepl replicates all snapshots, not only the ones it takes itself. It would be nice to have a feature to filter snapshots by name. This should be possible using the -i flag of zfs send. Would the non-zrepl snapshots be removed when pruning by time/last_n?

Issue #403 , one approach that solves it is in PR #459 but I'd rather have it be done in replication_logic.go

> 2 and 3

Yes, mid-term we want to decouple snapshot management from pruning.
Like you can do with the `snap` type job today, but without definiting `snapshotting` and `pruning` in the `push` job.

> 4

= "append-only sink"; The problem is that, due to how ZFS send/recv works under the hood, the receiver must already pretty much trust the sender completely. So, this would be nice to have but might also create a false sense of security here. It'd be only about preventing accidents in zrepl configuration.

> 5

For FreeBSD, there is #312 . Not sure whether we can do something similar on Linux. I personally run a zrepl push job  unprivileged on FreeBSD. 

> 6

You can implement this with a  sink-side `snap` job.

> 7

Shouldn't zfs do the buffering internally?


----


Please open individual issues for each item you want to discuss further.
