### ISSUE TITLE
[feature request] allow mixing sink datasets and pull in the same parent

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#580]
I have a ``zroot/encrypted/zrepl`` dataset. I would like to be able to store all my backups in that one.
When using a ``pull`` job, I need to manually create a ``zroot/encrypted/zrepl/host1`` child dataset and use it as ``root_fs: zroot/encrypted/zrepl/host1``.
When using a ``sink`` job, I would like to be able to ``root_fs: "zroot/encrypted/zrepl"``, which will create ``zroot/encrypted/zrepl/host2``.

As the ``pull`` job is only working on the child dataset, and doesn't touch the parent (doesn't it ?), it should not conflict with the ``sink`` job which doesn't touch to the parent either.

**Comment by problame** [comment]
> and doesn't touch the parent 

Correct.

---

The problem is that the `sink` takes the client identity from the `transport`, and for the TLS transport, the identity is the CN in the client certificate. So, the sink-side zrepl daemon can't check at startup time that pull and sink will never interfere.

Are you getting a concrete error right now, or are you simply asking for clarification?

(Sorry it took so long to respond here :( )

**Comment by problame** [comment]
Closing due to lack of response. If there is a too conservative check that's blocking your use case right now, we might debate removing it. In that case, please re-open this issue.
