### ISSUE TITLE
estimated size is often wrong 

### ISSUE THREAD

**Issue by silenius** [zrepl/zrepl#678]
Hello,

Not a big deal but estimated size if often wrong, see screenshot:

![zrepl](https://user-images.githubusercontent.com/1225348/215043786-97881451-9979-4c17-8432-860adf3216af.png)

(49MiB transferred vs 76.9MiB estimated)

**Comment by problame** [comment]
Please share the OS & ZFS version that you are using (zfs version), as well as [the zrepl `send` options](https://zrepl.github.io/configuration/sendrecvoptions.html?highlight=placeholders#send-options) that you are using.

**Comment by silenius** [comment]
Hello,

I'm backuping three hosts (`chimay`, `chouffe`, and `troubadour`) on a dedicated (remote) host (`stout`). Backup occurs in a dedicated jail (`zsync`) with a jailed dataset.

```sh
jcigar@stout:~ $ freebsd-version
13.1-RELEASE-p5
jcigar@stout:~ $ sudo zfs version
zfs-2.1.4-FreeBSD_g52bad4f23
zfs-kmod-2.1.4-FreeBSD_g52bad4f23
jcigar@stout:~ $ sudo jexec zsync freebsd-version
13.1-RELEASE-p2

chimay% freebsd-version
13.1-RELEASE-p3
chimay% sudo zfs version
zfs-2.1.4-FreeBSD_g52bad4f23
zfs-kmod-2.1.4-FreeBSD_g52bad4f23

chouffe% freebsd-version
12.3-RELEASE-p5

troubadour% freebsd-version
12.4-RELEASE
```

I don't have any particular send option, but I'm using `TCP` and `wireguard`

**Comment by problame** [comment]
Depending on your pruning policy, the first replication step in every attempt might be using a bookmark.
Due to lack of support for size estimation with bookmarks in old ZFS versions, zrepl currently doesn't do size estimation for bookmarks.
That would explain why the numbers are off.

But with your ZFS versions, size estimation with bookmarks would work.
See #649 for that work item.

I'll mark this as a dupe.
